const Constantes = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLECER_SESSION: 'ESTABLECER_SESSION',
  CERRAR_SESSION: 'CERRAR_SESSION',
  LIMPIAR_IMAGEN_SINGUP: 'LIMPIAR_IMAGEN_SINGUP',
  CARGAR_IMAGEN_SINGUP: ' CARGAR_IMAGEN_SINGUP',
  CLOUDINARY_NAME: 'https://api.cloudinary.com/v1_1/dt1gamctg/image/upload',
  CLOUDINARY_PRESET: 'urqrxunf',
  CARGAR_IMAGEN_PUBLICACION: 'CARGAR_IMAGEN_PUBLICACION',
  LIMPIAR_IMAGEN_PUBLICACION: 'LIMPIAR_IMAGEN_PUBLICACION'
};

export default Constantes;
