const Constantes = {
  REGISTRO: 'REGISTRO',
  LOGIN: 'LOGIN',
  ESTABLECER_SESSION: 'ESTABLECER_SESSION',
  CERRAR_SESSION: 'CERRAR_SESSION',
  LIMPIAR_IMAGEN_SINGUP: 'LIMPIAR_IMAGEN_SINGUP',
  CARGAR_IMAGEN_SINGUP: ' CARGAR_IMAGEN_SINGUP',
};

export default Constantes;
